name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Build (opcional)
      run: npm run build
      
    - name: Lint frontend
      run: |
        cd frontend
        npm ci
        npm run lint

    - name: Lint backend
      run: |
        cd ../backend
        npm ci
        npm run lint
